import { configs as perfectionistConfigs } from 'eslint-plugin-perfectionist';
import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    nursery: 'error',
    pedantic: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  env: { node: true },
  jsPlugins: ['eslint-plugin-perfectionist'],
  options: { reportUnusedDisableDirectives: 'error', typeAware: true },
  overrides: [
    {
      files: ['**/*.config.ts', '.release-it.ts'],
      rules: { 'import/no-anonymous-default-export': 'off', 'import/no-default-export': 'off' },
    },
  ],
  plugins: ['import', 'node', 'oxc', 'promise', 'typescript', 'unicorn'],
  rules: {
    ...perfectionistConfigs['recommended-natural'].rules,
    curly: ['error', 'multi-line'],
    'func-style': ['error', 'declaration', { allowArrowFunctions: true }],
    'import/exports-last': 'off',
    'import/group-exports': 'off',
    'import/no-named-export': 'off',
    'import/no-nodejs-modules': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/prefer-default-export': 'off',
    'init-declarations': 'off',
    'no-array-constructor': 'off',
    'no-duplicate-imports': 'off',
    'no-implied-eval': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'off',
    'no-magic-numbers': 'off',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off',
    'no-ternary': 'off',
    'no-throw-literal': 'off',
    'no-undefined': 'off',
    'node/no-process-env': 'off',
    'node/no-top-level-await': 'off',
    'one-var': ['error', 'never'],
    'oxc/no-async-await': 'off',
    'oxc/no-optional-chaining': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'prefer-destructuring': 'off',
    'prefer-promise-reject-errors': 'off',
    'prefer-spread': 'off',
    'require-await': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/prefer-find': 'off',
    'typescript/prefer-includes': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/prefer-regexp-exec': 'off',
    'typescript/prefer-string-starts-ends-with': 'off',
    'typescript/strict-boolean-expressions': 'off',
  },
});
